    - name: Check if Docker is installed
      shell: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Delete old Docker files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker.list.save
        - /etc/apt/keyrings/docker.asc
      when: docker_installed.rc != 0

    - name: Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: docker_installed.rc != 0

    - name: GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: "{{ docker_keyring }}"
        mode: '0644'
      when: docker_installed.rc != 0

    - name: Docker registry
      apt_repository:
        repo: "deb [arch=amd64 signed-by={{ docker_keyring }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present
        update_cache: yes
      when: docker_installed.rc != 0

    - name: docker-ce
      apt:
        name: docker-ce
        state: latest
      when: docker_installed.rc != 0

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes
      when: docker_installed.rc != 0

